language: php
sudo: false
services:
  - redis-server
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
cache:
  directories:
    - $HOME/.composer/cache
matrix:
  include:
    - php: hhvm
script: vendor/bin/phpunit --debug