language: php
sudo: false
services: redis-server
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
dist: trusty